Clase 02: De los datos al insight

In [29]:
# Preliminares 

import kagglehub
import os
import pandas as pd 
from IPython.display import display, HTML

## DATOS

In [30]:
# Descarga 

path = kagglehub.dataset_download("vakhariapujan/avocado-prices-and-sales-volume-2015-2023")
print("Path to dataset files:", path)

Warning: Looks like you're using an outdated `kagglehub` version (installed: 0.3.13), please consider upgrading to the latest version (1.0.0).
Path to dataset files: C:\Users\ASUS\.cache\kagglehub\datasets\vakhariapujan\avocado-prices-and-sales-volume-2015-2023\versions\3

In [31]:
print(os.listdir(r"C:\Users\ASUS\.cache\kagglehub\datasets\vakhariapujan\avocado-prices-and-sales-volume-2015-2023\versions\3"))

['Avocado_HassAvocadoBoard_20152023v1.0.1.csv']

In [32]:

palta = pd.read_csv(os.path.join(path, "Avocado_HassAvocadoBoard_20152023v1.0.1.csv"))

In [33]:
# Chequeo del data set

palta.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53415 entries, 0 to 53414
Data columns (total 12 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Date          53415 non-null  object
 1   AveragePrice  53415 non-null  float64
 2   TotalVolume   53415 non-null  float64
 3   plu4046       53415 non-null  float64
 4   plu4225       53415 non-null  float64
 5   plu4770       53415 non-null  float64
 6   TotalBags     53415 non-null  float64
 7   SmallBags     41025 non-null  float64
 8   LargeBags     41025 non-null  float64
 9   XLargeBags    41025 non-null  float64
 10  type          53415 non-null  object
 11  region        53415 non-null  object
dtypes: float64(9), object(3)
memory usage: 4.9+ MB

In [39]:
# Nulos 

print("\n== CAMPOS NULOS=====\n") 

palta.isnull().sum()

== CAMPOS NULOS=====

Date                0
AveragePrice        0
TotalVolume         0
plu4046             0
plu4225             0
plu4770             0
TotalBags           0
SmallBags       12390
LargeBags       12390
XLargeBags      12390
type                0
region              0
dtype: int64

In [35]:
# Vista rápida — primeras y últimas filas


display(palta.head(3))
display(palta.tail(3))

,Date,AveragePrice,TotalVolume,plu4046,plu4225,plu4770,TotalBags,SmallBags,LargeBags,XLargeBags,type,region
0,2015-01-04,1.22,40873.28,2819.50,28287.42,49.90,9716.46,9186.93,529.53,0.0,conventional,Albany
1,2015-01-04,1.79,1373.95,57.42,153.88,0.00,1162.65,1162.65,0.00,0.0,organic,Albany
2,2015-01-04,1.00,435021.49,364302.39,23821.16,82.15,46815.79,16707.15,30108.64,0.0,conventional,Atlanta

,Date,AveragePrice,TotalVolume,plu4046,plu4225,plu4770,TotalBags,SmallBags,LargeBags,XLargeBags,type,region
53412,2023-12-03,1.618931,34834.86,15182.42,1211.38,0.00,18075.66,NaN,NaN,NaN,organic,WestTexNewMexico
53413,2023-12-03,1.245406,2942.83,1058.54,7.46,0.00,1779.19,NaN,NaN,NaN,organic,Wichita
53414,2023-12-03,1.479240,2010020.72,271808.32,274480.64,63.43,1364514.02,NaN,NaN,NaN,organic,TotalUS